import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next forum project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} navbar`}>
        <Link href='/' className='logo'>NEXT Forum</Link>
        <Link href='/list'>List</Link>
        {children}
      </body>
    </html>
  );
}
